eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true #是否显示IP
spring:
  zipkin:
    base-url: http://localhost:9411
#    sender:
#      type: web #zipkin客户端发送消息的方式，http的方式(如果有spring-cloud-starter-bus-amqp组件,那么采用的是rabbitmq方式)
  sleuth:
    sampler:
      probability: 1.0 #收集追踪信息的比率，如果是0.1则表示只记录10%的追踪数据，如果要全部追踪，设置为1（实际场景不推荐，因为会造成不小的性能消耗）
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
# 手动刷新配置信息
management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点 默认是info,health