eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true #是否显示IP
    metadata-map:
      cluster: consumers  #对应聚合涡轮监控--类似集群
#shutdown端点可以用来远程关闭应用，此端点默认是关闭的，如果使用的话，需要开启，使用以下属性
#你就可以在应用启动后远程通过调用/actuator/shutdown来关闭应用，注意只能POST请求调用。
#  endpoint:
#    shutdown:
#      enabled: true
# feign
feign:
  client:
    config:
      default:
        connectTimeout: 7000
        readTimeout: 7000
  hystrix:
    enabled: true #开启Feign的熔断功能(默认情况下是关闭的)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000 # 设置hystrix的超时时间为8000ms
#zipkin
spring:
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web #zipkin客户端发送消息的方式，必须有
  sleuth:
    sampler:
      probability: 1.0 #收集追踪信息的比率，如果是0.1则表示只记录10%的追踪数据，如果要全部追踪，设置为1（实际场景不推荐，因为会造成不小的性能消耗）