server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
#        native:
#          searchLocations: file:E:/native-config-repo
        git:
          uri: https://github.com/elvesfish/microservice-config
          username:
          password:
          search-paths: repo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#关闭刷新安全认证
management:
  security:
    enabled: false
#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}



