server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
#        native:
#          searchLocations: file:E:/native-config-repo
        git:
          uri: https://github.com/elvesfish/microservice-config
          search-paths: repo
#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true #是否显示IP



