server:
  port: 5000
spring:
  application:
    name: ms-server-admin
  security: #sba-ui login登录
    user:
      name: admin
      password: admin
eureka:
  client:
    registryFetchIntervalSeconds: 5 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10 #表示eureka client发送心跳给server端的频率，默认为30秒
    health-check-url-path: /actuator/health #健康检查的地址（依赖spring-boot-starter-actuator）
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #实例ID,显示IP
    prefer-ip-address: true #是否显示IP
#端点开放
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS #健康检查快速

